# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20161106_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='is_present',
        ),
    ]
